In [2]:
import pandas as pd

In [24]:
from sqlalchemy import create_engine
engine = create_engine('sqlite://')
student_productivity.to_sql('my_table', engine, index=False)

20000

In [26]:
student_productivity = pd.read_csv(r"C:\Users\sukai\Downloads\archive (3).zip")
student_productivity.head()
student_productivity.shape

(20000, 18)

In [4]:
student_productivity.study_hours_per_day

0        4.35
1        6.14
2        4.98
3        3.19
4        7.67
         ...
19995    4.81
19996    0.83
19997    9.36
19998    0.74
19999    3.64
Name: study_hours_per_day, Length: 20000, dtype: float64

In [5]:
student_productivity["study_hours_per_day"]

0        4.35
1        6.14
2        4.98
3        3.19
4        7.67
         ...
19995    4.81
19996    0.83
19997    9.36
19998    0.74
19999    3.64
Name: study_hours_per_day, Length: 20000, dtype: float64

In [6]:
student_productivity.age[10]

np.int64(23)

In [7]:
student_productivity["exercise_minutes"][100]

np.int64(46)

In [8]:
student_productivity.breaks_per_day.iloc[:]

0         6
1        13
2         1
3         9
4         8
         ..
19995     6
19996     1
19997     4
19998     7
19999     8
Name: breaks_per_day, Length: 20000, dtype: int64

In [9]:
student_productivity.assignments_completed.iloc[1000]

np.int64(10)

In [10]:
student_productivity.iloc[1:6, 6]

1    1.51
2    3.63
3    3.95
4    1.59
5    3.74
Name: social_media_hours, dtype: float64

In [11]:
student_productivity.iloc[-876]

student_id                19125
age                          23
gender                   Female
study_hours_per_day        0.57
sleep_hours                3.22
phone_usage_hours          4.26
social_media_hours         5.85
youtube_hours              3.36
gaming_hours               0.71
breaks_per_day                5
coffee_intake_mg            234
exercise_minutes             62
assignments_completed         1
attendance_percentage     56.59
stress_level                  9
focus_score                  88
final_grade               81.35
productivity_score        25.95
Name: 19124, dtype: object

In [12]:
student_productivity.loc[567, "attendance_percentage"]

np.float64(82.23)

In [13]:
student_productivity.loc[3, ["study_hours_per_day", "phone_usage_hours", "sleep_hours"]]

study_hours_per_day     3.19
phone_usage_hours      10.06
sleep_hours             4.58
Name: 3, dtype: object

In [14]:
student_productivity.set_index("age")

,student_id,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
age,,,,,,,,,,,,,,,,,
23,1,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
20,2,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
29,3,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
27,4,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
24,5,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,19996,Female,4.81,7.83,6.86,6.93,2.77,5.68,6,451,0,11,63.69,3,89,82.13,60.43
22,19997,Other,0.83,4.49,6.76,3.79,2.95,1.38,1,375,13,4,74.06,10,56,87.12,17.84
25,19998,Male,9.36,4.33,2.94,6.98,0.35,1.42,4,413,1,11,73.18,9,69,81.58,65.56
22,19999,Female,0.74,4.44,3.15,5.99,3.11,5.01,7,319,1,6,77.02,5,53,53.04,28.06
19,20000,Female,3.64,6.35,8.68,0.11,5.19,1.28,8,50,70,9,40.08,9,65,72.70,30.37

In [15]:
student_productivity.loc[(student_productivity.gender == "Female") & (student_productivity.coffee_intake_mg > 300)]

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
9,10,19,Female,7.28,9.56,2.13,0.81,1.35,2.55,7,416,107,6,79.15,10,73,88.53,73.18
19,20,22,Female,4.61,9.58,3.13,6.76,2.43,2.27,3,499,27,5,40.50,4,32,62.96,47.04
29,30,28,Female,4.10,8.97,3.58,4.02,0.06,4.15,3,475,17,11,61.87,7,93,58.80,62.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19982,19983,27,Female,3.16,6.45,4.31,7.47,5.05,5.54,11,339,49,13,45.44,10,70,80.90,37.05
19984,19985,23,Female,3.90,4.25,5.07,4.97,0.84,5.79,4,343,17,7,87.14,2,31,73.92,35.84
19991,19992,28,Female,2.72,5.55,4.66,2.70,3.77,2.52,11,332,73,11,61.53,10,78,91.75,37.35
19995,19996,26,Female,4.81,7.83,6.86,6.93,2.77,5.68,6,451,0,11,63.69,3,89,82.13,60.43
19998,19999,22,Female,0.74,4.44,3.15,5.99,3.11,5.01,7,319,1,6,77.02,5,53,53.04,28.06

In [16]:
student_productivity.loc[(student_productivity.sleep_hours >= 3.00) & (student_productivity.phone_usage_hours > 3.00)]

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,19995,20,Male,9.84,4.99,5.27,0.70,2.11,1.44,9,340,49,1,99.33,5,78,82.19,77.10
19995,19996,26,Female,4.81,7.83,6.86,6.93,2.77,5.68,6,451,0,11,63.69,3,89,82.13,60.43
19996,19997,22,Other,0.83,4.49,6.76,3.79,2.95,1.38,1,375,13,4,74.06,10,56,87.12,17.84
19998,19999,22,Female,0.74,4.44,3.15,5.99,3.11,5.01,7,319,1,6,77.02,5,53,53.04,28.06
19999,20000,19,Female,3.64,6.35,8.68,0.11,5.19,1.28,8,50,70,9,40.08,9,65,72.70,30.37

In [17]:
student_productivity.loc[student_productivity.focus_score.isin([57, 49])]

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
54,55,20,Female,2.08,3.04,10.22,5.73,3.48,1.56,4,115,109,5,72.68,5,57,70.64,19.22
105,106,25,Male,6.85,4.12,2.00,4.04,2.51,1.40,5,105,32,0,51.51,3,57,83.20,54.76
127,128,23,Female,4.12,9.36,9.42,3.85,4.98,4.25,6,65,70,17,65.74,4,57,99.14,46.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19856,19857,27,Female,6.20,9.56,1.20,1.49,3.28,4.72,10,313,83,5,98.83,6,49,62.60,69.76
19859,19860,17,Male,9.33,4.67,8.29,2.96,3.80,2.28,9,111,21,15,53.17,6,49,70.55,51.21
19882,19883,26,Male,4.09,3.09,8.23,5.55,4.02,4.12,6,238,38,19,85.95,10,57,70.51,28.00
19923,19924,23,Male,3.27,6.94,4.92,6.88,2.53,3.78,9,45,69,6,84.91,2,57,74.32,48.67
19933,19934,17,Male,4.65,4.16,9.60,3.35,0.42,1.22,9,294,65,16,60.16,2,57,63.81,35.55

In [18]:
student_productivity["assignments_completed"] = 10
student_productivity

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,10,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,10,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,10,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,10,45.53,6,41,90.13,52.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,26,Female,4.81,7.83,6.86,6.93,2.77,5.68,6,451,0,10,63.69,3,89,82.13,60.43
19996,19997,22,Other,0.83,4.49,6.76,3.79,2.95,1.38,1,375,13,10,74.06,10,56,87.12,17.84
19997,19998,25,Male,9.36,4.33,2.94,6.98,0.35,1.42,4,413,1,10,73.18,9,69,81.58,65.56
19998,19999,22,Female,0.74,4.44,3.15,5.99,3.11,5.01,7,319,1,10,77.02,5,53,53.04,28.06
19999,20000,19,Female,3.64,6.35,8.68,0.11,5.19,1.28,8,50,70,10,40.08,9,65,72.70,30.37

In [19]:
student_productivity["exercise_minutes"] = range(len(student_productivity.exercise_minutes),0,-1)
student_productivity["exercise_minutes"]

0        20000
1        19999
2        19998
3        19997
4        19996
         ...
19995        5
19996        4
19997        3
19998        2
19999        1
Name: exercise_minutes, Length: 20000, dtype: int64

In [29]:
query = """
SELECT gender, final_grade, productivity_score FROM my_table
ORDER BY gender asc
LIMIT 10;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table)

   gender  final_grade  productivity_score
0  Female        81.87               33.78
1  Female        86.22               36.60
2  Female        71.77               19.87
3  Female        62.71               41.23
4  Female        52.22               53.81
5  Female        88.53               73.18
6  Female        73.23               59.99
7  Female        62.96               47.04
8  Female        84.31               32.60
9  Female        82.13               35.45

In [30]:
query = """
SELECT assignments_completed, attendance_percentage FROM my_table
ORDER BY final_grade asc
LIMIT 3 OFFSET 100;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table)

   assignments_completed  attendance_percentage
0                     10                  50.29
1                     10                  50.55
2                     10                  53.27

In [32]:
query = """
SELECT DISTINCT age FROM my_table ORDER BY age asc;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table)

    age
0    17
1    18
2    19
3    20
4    21
5    22
6    23
7    24
8    25
9    26
10   27
11   28
12   29