In [1]:
import pandas as pd

In [2]:
student_productivity = pd.read_csv(r"C:\Users\sukai\Downloads\archive (2).zip")
student_productivity.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [19]:
student_distraction = pd.read_csv(r"C:\Users\sukai\Downloads\archive (3).zip")
student_distraction.head()

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

In [7]:
#rename
renamed = student_productivity.rename(columns=({"academic_level":"school_level"}))
renamed.head()

,student_id,age,gender,school_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [17]:
#rename rows and columns
rename = student_distraction.rename_axis("ID", axis = "rows")
rename.head()

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
ID,,,,,,,,,,,,,,,,,,
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

In [20]:
#combining
#concat()
combined_data = pd.concat([student_productivity, student_distraction])
combined_data.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,study_hours_per_day,phone_usage_hours,youtube_hours,breaks_per_day,coffee_intake_mg,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#join
left = student_productivity
right = student_distraction
left.join(right, lsuffix = "_p", rsuffix = "_d")

,student_id_p,age_p,gender_p,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours_p,gaming_hours_p,sleep_hours_p,...,gaming_hours_d,breaks_per_day,coffee_intake_mg,exercise_minutes_d,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score_d
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,5.65,8,436,105,7,45.53,6,41,90.13,52.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,20,Other,Undergraduate,3.93,1.42,0.54,2.58,2.62,9.30,...,3.46,7,189,11,14,76.64,7,57,74.19,62.63
4996,4997,24,Male,High School,4.00,0.00,3.00,4.45,2.47,6.42,...,0.56,13,164,43,8,85.53,10,45,59.15,48.56
4997,4998,22,Male,Undergraduate,5.63,2.52,2.89,3.58,1.07,6.65,...,2.15,11,46,98,0,64.08,3,32,68.01,47.47
4998,4999,17,Male,Undergraduate,3.58,2.83,1.53,5.88,1.28,7.36,...,0.08,13,403,42,5,52.80,5,91,56.76,55.41
4999,5000,22,Other,Undergraduate,5.60,4.14,2.17,3.05,2.74,6.38,...,5.64,4,312,24,5,93.40,9,52,45.79,26.12